config/routes.rb
Rails.application.routes.draw do
  
  namespace :admins do
    resources :products
    resources :site_banners
    
    put "/products/:id/show_state"=>"products#show_state",as: :products_show_state
    post "/site/address_create" => "site#address_create"
    get "/site/address_new" => "site#address_new"
    get "/site/address/:id/edit" => "site#address_edit" , as: :site_address_edit
    put "/site/address/address_update" => "site#address_update", as: :site_address

    post "/site/about_us_create"=>"site#about_us_create"
    get "/site/about_us_new"=>"site#about_us_new"
    get "/site/about_us/:id/edit"=>"site#about_us_edit"
    put "/site/about_us/about_us_update"=>"site#about_us_update", as: :site_about_us

    post "/site/service_create"=>"site#service_create"
    get "/site/service_new"=>"site#service_new"
    get "/site/service/:id/edit"=>"site#service_edit"
    put "/site/service/service_update"=>"site#service_update", as: :site_service

    post "/site/contact_create"=>"site#contact_create"
    get "/site/contact_new"=>"site#contact_new"
    get "/site/contact/:id/edit"=>"site#contact_edit"
    put "/site/contact/contact_update"=>"site#contact_update", as: :site_contact

    post "/site/upload"=>"site#upload"
  end

  devise_for :admins, controllers: { sessions: "admins/sessions" }

  root 'home#index'

  resources :products,only:[:index,:show]
  resources :contact,only:[:index]
  resources :about_us,only:[:index]
  resources :service,only:[:index]

end

app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Timestamps
  paginates_per 10

  scope :list, -> {where(status:1,is_show: 1).order("updated_at desc")}
  scope :main_products, -> {where(status:1,is_show: 1,is_single: 1).order("updated_at desc")}
  scope :list_products, -> {where(status:1,is_show: 1,is_recommend: 1).order("updated_at desc")}
  scope :left_products, -> {where(status:1,is_show: 1,is_show_left: 1).order("updated_at desc")}
  
  field :cover_url, type: String
  field :description, type: String
  field :name, 	type: String
  field :is_show, type: Integer
  field :status, type: Integer,default: 1
  field :is_single, type: Integer, default: 0 #是否首页单个显示
  field :is_recommend,  type: Integer, default:0 #是否推荐到首页
  field :is_show_left, type: Integer, default:0 #是否显示在右侧栏

  validates :name, presence: true
  validates :is_show, presence: true
  validates :cover_url, presence: true
end

app/controllers/admins/products_controller.rb
#encoding: utf-8
class Admins::ProductsController < Admins::BaseController
  before_action :set_admins_product, only: [:show_state,:edit, :update, :destroy]

  include Concerns::Admins::FindByParams
  include Concerns::Admins::ImageUpload

  respond_to :html

  def index
    query = build_query(params.clone)
    @products = Product.where(query).order("created_at desc").page(params[:page])
    respond_with(@products)
  end

  def new
    @product = Product.new
    respond_with(@product)
  end

  def edit
  end

  def create
    hash = admins_product_params
    hash[:cover_url] = upload_cover_img(params[:product][:cover_url],upload_path)
    @product = Product.new(hash)
    if @product.save
      redirect_to admins_products_path, notice: '新增成功！'
    else
      respond_with(@product)
    end
  end

  def update
    hash = admins_product_params
    if params[:product][:cover_url].present?
      hash[:cover_url] = upload_cover_img(params[:product][:cover_url],upload_path)
    else
      hash[:cover_url] = params.permit(:old_cover_url)[:old_cover_url]
    end
    @product.update!(hash)
    redirect_to "/admins/products/",:notice=>"编辑成功！"
  end

  def show_state
    @product.update_attributes(del_empty)
    render json: {code: 200,text: "更新成功！"}
  end

  def destroy
    @product.destroy
    redirect_to "/admins/products",notice: "删除成功！"
  end

  private
    def set_admins_product
      @product = Product.find(params[:id])
    end

    def admins_product_params
      params.require(:product).permit(:name,:is_show,:cover_url,:description,:is_single,:is_recommend,:is_show_left)
    end

    def del_empty
      hash = params.permit(:is_single,:is_recommend,:is_show_left,:status)
      hash.map do |k,v|
        hash.delete(k) if hash[k].blank?
      end
      hash
    end

    def upload_path
      date = Time.now.strftime("%y/%m/%d")
      path = "#{Setting.file_path}#{date}/"
      FileUtils.mkdir_p(path) unless Dir.exist?(path)
      path
    end
    
end

app/controllers/products_controller.rb
#encoding: utf-8
class ProductsController < ParentController
  def index
    @products = Product.list.page(params[:page])
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
	def build_admin_product path,method
		"#{path}/#{method == :put ? @product.id : "" }"
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/products/_form.html.erb
<%= form_for(@product,url: build_admin_product(admins_products_path,method), html:{class: "form-horizontal",:multipart => true}) do |f| %>
  <% if @product.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
      <h2><%= pluralize(@product.errors.count, "error") %> 当前新增内容没有被保：</h2>
      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">产品名字</label>
    <div class="col-sm-10">
      <%=f.text_field(:name,class: "col-xs-8",placeholder: "产品名字")%>
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">产品封面</label>
    <div class="col-sm-10">
      <%=f.file_field(:cover_url)%>
    </div>
  </div>
  <%if method == :put%>
    <input type="hidden" id="old_cover_url" name="old_cover_url" value="<%=@product.cover_url%>">
    <div class="form-group">
      <label for="inputCoverUrl" class="col-sm-2 control-label">当前封面</label>
      <div class="col-sm-10"> 
        <%=image_tag(@product.cover_url,style: "height: 120px; width:300px; display:block")%>    
      </div>
    </div>
  <%end %>
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">是否显示</label>
    <div class="col-sm-10">
    <label class="radio-inline">
      <%=radio_button("product", "is_show", 1,checked:"checked")%> 是
    </label>
    <label class="radio-inline">
      <%=radio_button("product", "is_show", 0)%> 否
    </label>
  </div>
  </div>
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">描述</label>
    <div class="col-sm-10">
      <%=text_area(:product, :description, size: "80x10")%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= submit_tag "提交", :class => "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/admins/products/edit.html.erb
<h1>编辑产品</h1>

<%= render 'form',{method: :put} %>

<%= link_to '返回', admins_products_path %>

app/views/admins/products/index.html.erb
<br>
<div class="col-lg-12">
<form class="form-inline" role="form" action="/admins/products" method="get">
    <div class="form-group">
      <label class="sr-only" for="user_id">产品名称</label>
      <input type="text" class="form-control" name="name" id="name"  value="<%=@name%>" placeholder="产品名字">
    </div>
    <button type="submit" class="btn btn-default">查询</button>
  </form>
<br>
<%unless notice.blank? %>
  <div class="alert alert-success" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
    <p id="notice"><%= notice %></p>
  </div>
<%end%>
</div>
<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
       产品列表
    </div>
    <div class="panel-body">
      <div class="table-responsive">
        <%if @products.present?%>
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <td>封面</td>
              <td>产品名字</td>
              <td>是否显示</td>
              <td>是否在售</td>
              <td>显示到首页</td>
              <td>显示到首页list</td>
              <td>显示到右侧list</td>
              <td>操作</td>
            </tr>
          </thead>
          <tbody>
            <% @products.each do |product| %>
              <tr>
                <td>
                  <%=image_tag(product.cover_url,style: "height: 120px; width: 100px; display: block;")%>
                </td>
                <td><%=product.name%></td>
                <td><%= product.is_show == 1 ? "是": "否"%></td>
                <td><%= product.status == 1 ? "是": "否"%></td>
                <td>
                  <a href="javascript:void(0);" data-id="<%=product.id%>" data-is-single="<%=product.is_single%>" class="btn btn-<%=product.is_single==1 ? "danger" : "default" %> single">
                    <%=product.is_single == 1 ? "隐藏" : "显示"%>
                  </a>
                </td>
                <td>
                  <a href="javascript:void(0);" data-id="<%=product.id%>"  data-is-recommend="<%=product.is_recommend%>" class="btn btn-<%=product.is_recommend==1 ? "danger" : "default" %> recommend">
                    <%=product.is_recommend == 1 ? "隐藏" : "显示"%>
                  </a>
                </td>
                <td>
                  <a href="javascript:void(0);" data-id="<%=product.id%>"  data-is-show-left="<%=product.is_show_left%>" class="btn btn-<%=product.is_show_left==1 ? "danger" : "default" %> show-left ">
                    <%=product.is_show_left == 1 ? "隐藏" : "显示"%>
                  </a>
                </td>
                <td>
                  <%= link_to '编辑', edit_admins_product_path(product) %>
                  <a href="javascript:void(0);" data-id="<%=product.id%>"  data-status="<%=product.status%>" class="btn btn-link status ">
                    <%= product.status == 0 ? "上架" : "下架" %>
                  </a>
                  <%= link_to '删除', "/admins/products/#{product.id}", method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%else%>
          真懒，还没有添加产品呢！赶紧<%= link_to"添加",new_admins_product_path%>吧！
        <%end%>
      </div>
      <%if @products.present?%>
        <div align="center">
          <%= paginate @products, :window => 3 %> 
        </div>
      <%end%>
    </div>
  </div>
<%= link_to '添加产品', new_admins_product_path,class: "btn btn-default" %>
</div>

<p><strong>Note:</strong></p>
<p><span style="color:red">"显示/隐藏到首页"</span>表示该商品会在首页的单个商品区域显示；如果没有商品在首页单个商品区域显示，则改区域会为空</p>
<p><span style="color:red">"显示/隐藏到首页list"</span>表示该商品会在首页的多个商品区域显示；如果没有商品在首页多个商品区域显示，则改区域会为空</p>
<p><span style="color:red">"显示/隐藏到左侧list"</span>表示该商品会在首页的多个商品区域显示；如果没有商品在首页多个商品区域显示，则改区域会为空</p>

<%=content_for :js do %>
<%= javascript_include_tag "admins/products" %>
<%end%>

app/views/admins/products/new.html.erb
<h1>新增产品</h1>

<%= render 'form',{:method=>"post"} %>

<%= link_to '返回', admins_products_path %>