config/routes.rb
Rails.application.routes.draw do
  
  namespace :admins do
    resources :products
    resources :site_banners
    
    put "/products/:id/show_state"=>"products#show_state",as: :products_show_state
    post "/site/address_create" => "site#address_create"
    get "/site/address_new" => "site#address_new"
    get "/site/address/:id/edit" => "site#address_edit" , as: :site_address_edit
    put "/site/address/address_update" => "site#address_update", as: :site_address

    post "/site/about_us_create"=>"site#about_us_create"
    get "/site/about_us_new"=>"site#about_us_new"
    get "/site/about_us/:id/edit"=>"site#about_us_edit"
    put "/site/about_us/about_us_update"=>"site#about_us_update", as: :site_about_us

    post "/site/service_create"=>"site#service_create"
    get "/site/service_new"=>"site#service_new"
    get "/site/service/:id/edit"=>"site#service_edit"
    put "/site/service/service_update"=>"site#service_update", as: :site_service

    post "/site/contact_create"=>"site#contact_create"
    get "/site/contact_new"=>"site#contact_new"
    get "/site/contact/:id/edit"=>"site#contact_edit"
    put "/site/contact/contact_update"=>"site#contact_update", as: :site_contact

    post "/site/upload"=>"site#upload"
  end

  devise_for :admins, controllers: { sessions: "admins/sessions" }

  root 'home#index'

  resources :products,only:[:index,:show]
  resources :contact,only:[:index]
  resources :about_us,only:[:index]
  resources :service,only:[:index]

end

app/models/about_us.rb
#encoding: utf-8
class AboutUs
  include Mongoid::Document
  include Mongoid::Timestamps
  field :content, type: String
  validates :content, presence: true
  
end

app/models/address.rb
class Address
  include Mongoid::Document
  include Mongoid::Timestamps
  field :content, type: String
  validates :content, presence: true
end

app/models/admin.rb
class Admin
  include Mongoid::Document
  include Mongoid::Timestamps
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/models/contact.rb
#encoding: utf-8
class Contact
  include Mongoid::Document
  include Mongoid::Timestamps
  field :content, type: String
  validates :content, presence: true
end

app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Timestamps
  paginates_per 10

  scope :list, -> {where(status:1,is_show: 1).order("updated_at desc")}
  scope :main_products, -> {where(status:1,is_show: 1,is_single: 1).order("updated_at desc")}
  scope :list_products, -> {where(status:1,is_show: 1,is_recommend: 1).order("updated_at desc")}
  scope :left_products, -> {where(status:1,is_show: 1,is_show_left: 1).order("updated_at desc")}
  
  field :cover_url, type: String
  field :description, type: String
  field :name, 	type: String
  field :is_show, type: Integer
  field :status, type: Integer,default: 1
  field :is_single, type: Integer, default: 0 #是否首页单个显示
  field :is_recommend,  type: Integer, default:0 #是否推荐到首页
  field :is_show_left, type: Integer, default:0 #是否显示在右侧栏

  validates :name, presence: true
  validates :is_show, presence: true
  validates :cover_url, presence: true
end

app/models/service.rb
class Service
  include Mongoid::Document
  include Mongoid::Timestamps
  field :content, type: String
end

app/models/setting.rb
class Setting < Settingslogic
  source "#{Rails.root}/config/config.yml"
  namespace Rails.env

end

app/models/site_banner.rb
#encoding:utf-8
class SiteBanner
  include Mongoid::Document
  include Mongoid::Timestamps
  scope :default,->{order("created_at desc")}
  field :base_url, type: String
end

app/controllers/about_us_controller.rb
#encoding: utf-8
class AboutUsController < ParentController
  def index
    @obj = AboutUs.first
  end
end

app/controllers/admins/base_controller.rb
#encoding: utf-8
class Admins::BaseController < ApplicationController

	layout "admin"
	before_action :authenticate_admin!,:set_active

	def set_active
    controller = params["controller"].gsub("/","_")
    self.instance_variable_set("@#{controller}", 'active')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :init_share_component

  def after_sign_in_path_for(resource)
    sign_in_url = url_for(:action => 'new', :controller => 'sessions', :only_path => false, :protocol => 'http')
    if request.url == sign_in_url
       "/admins/products"
  	else
  		super
    end
  end

  def init_share_component
    @address = Address.last
    @banners = SiteBanner.default
  end
end

app/controllers/contact_controller.rb
#ecoding: utf-8
class ContactController < ParentController
  def index
    @obj = Contact.first
  end
end

app/controllers/home_controller.rb
#encoding: utf-8
class HomeController < ApplicationController
	include Concerns::HomeConcerns
	include Concerns::ProductConcerns

	def index
	   main_products
     about_us
	   product_list
	end
end

app/controllers/parent_controller.rb
#encoding: utf-8
class ParentController < ApplicationController
  before_filter :get_left_product_menu,:contact_us
  
  private
    def get_left_product_menu
      @products_menu = Product.left_products
    end
    def contact_us
      @contact = Contact.last
    end
end

app/controllers/products_controller.rb
#encoding: utf-8
class ProductsController < ParentController
  def index
    @products = Product.list.page(params[:page])
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/service_controller.rb
#encoding: utf-8
class ServiceController < ParentController
  def index
    @obj = Service.first
  end
end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
	def build_admin_product path,method
		"#{path}/#{method == :put ? @product.id : "" }"
	end
end

app/helpers/admins/site_helper.rb
#encoding: utf-8
module Admins::SiteHelper
	def form_method action
		action  == "create" ? "post" : "put"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_banners.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <%@banners.each_with_index do |b,i|%>
      <li data-target="#carousel-example-generic" data-slide-to="<%=i%>" class="<%='active' if i == 0 %>"></li>
    <%end%>
  </ol>
  <div class="carousel-inner" role="listbox">
    <%@banners.each_with_index do |banner,index|%>
      <div class="item <%='active' if index == 0 %>">
        <img src="<%=banner.base_url%>" width="970px">
      </div>
    <%end%>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer-container">
        <footer class="footer clearfix">
            <p><%=@address.content%></p>
        </footer>
</div>

app/views/layouts/_header.html.erb
<div class="header-container">
	<header class="wrapper clearfix">
	<a href="/"><%=image_tag("logo.png",width:"350px;margin: 12px 0 10px 20px;")%></a>
  	<nav>
  		<ul id="menu" class="dropdown dropdown-upward">
  			<li id="menu-item-44" class="first menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-44">
  				<a href="/">HOME</a>
  			</li>
				<li id="menu-item-45" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-45">
					<%=link_to("ABOUT US","/about_us.html")%>
				</li>
				<li id="menu-item-49" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-49">
					<%=link_to "PRODUCT", "/products.html"%>
				</li>
				<li id="menu-item-48" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-48">
					<%=link_to("SERVICE","/service.html")%>
				</li>
				<li id="menu-item-47" class="last menu-item menu-item-type-post_type menu-item-object-page menu-item-47">
				<%=link_to("CONTACT","/contact.html")%>
				</li>
			</ul>
		</nav>
   </header>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SOS管理后台</title>
  <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
  <%if admin_signed_in?%>
    <%=render "layouts/admin/navgation"%>
  <%end%>
  <div id="<%='page-wrapper' if admin_signed_in?%>">
    <%= yield %>
  </div>
</div>
<%= yield(:js)%>
</body>
</html>

app/views/layouts/admin/_navgation.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">SOS管理后台</a>
  </div>
  <ul class="nav navbar-top-links navbar-right">
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <%=current_admin.email%>
          <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
          <li>
            <%= link_to destroy_admin_session_path do %>
              <i class="fa fa-wrench fa-fw"></i>退出
            <%end%>
          </li>
        </ul>
    </li>
  </ul>
  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
        <li class="<%=@admins_products%>">
          <a href="#" class="<%=@admins_products%>">
            <i class="fa fa-table fa-fw"></i>产品管理<span class="fa arrow"></span>
          </a>
          <ul class="nav nav-second-level collapse">
              <li>
                <%=link_to "产品列表",admins_products_path%>
              </li>
              <li>
                <%=link_to "新增分类",new_admins_product_path%>
              </li>
          </ul>
        </li>
        <li class="<%=@admins_site%>">
          <a href="#" class="<%=@admins_site%>">
            <i class="fa fa-edit fa-fw"></i>网站管理<span class="fa arrow"></span>
          </a>
          <ul class="nav nav-second-level collapse">
              <li>
                <%=link_to "服务",admins_site_service_new_path%>
              </li>
              <li>
                <%=link_to "关于我们",admins_site_about_us_new_path%>
              </li>
              <li>
                <%=link_to "联系我们",admins_site_contact_new_path%>
              </li>
              <li>
                <%=link_to "页脚地址",admins_site_address_new_path%>
              </li>
          </ul>
        </li>
        <li class="<%=@admins_site_banners%>">
          <a href="#" class="<%=@admins_site_banners%>">
            <i class="fa fa-wrench fa-fw"></i>网站banner管理<span class="fa arrow"></span>
          </a>
          <ul class="nav nav-second-level collapse">
              <li>
                <%=link_to "新增banner",new_admins_site_banner_path%>
              </li>
              <li>
                <%=link_to "banners",admins_site_banners_path%>
              </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%=yield :title%>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="body">
    <%=render "layouts/header"%>
    <div class="content clearfix">
      <%=render "layouts/banners"%>
      <%= yield %>
    </div>
    <%=render "layouts/footer"%>
  </div>
</body>
</html>

app/views/shareds/_content.html.erb
<div class="col-md-9">
  <div class="content-body">
    <%= raw @obj.content.html_safe %>
  </div>
</div>
<style type="text/css">
  .col-md-9{
    margin-top: 17px;
  }
	p{margin-top: 0px;margin-bottom: 5px}
</style>

app/views/shareds/_left.html.erb
<div class="col-md-3">
  <nav class="nav-bar">
    <dl> 
      <dt class="left-nav-header">PRODUCT</dt>
      <% @products_menu.each do |prod|%>
        <dd id="left-list-products"><%=link_to(prod.name,product_path(prod.id))%></dd> 
      <%end%>
    </dl> 
  </nav>

  <nav class="nav-bar">
    <dl> 
      <dt class="left-nav-header">CONTACT US</dt>
      <p>
          <strong>SOS MARINE SERVICE CO.,LTD</strong>
      </p>
      <p>
          <span>No.115,Chuansha Road Heqing Town,PuDong New District ,City Shanghai,China</span>
      </p>
      <p>
          <span >Tel:021-63576648</span>
      </p>
      <p>
          <span>Fax:021-63786625</span>
      </p>
      <p>
        <span>E-Mail:info@sos-marineservice.com</span>
      </p>
    </dl> 
  </nav>
</div>